// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgvi7_KlIXxcJAdAXF-h7XEnBF48T6u8',
    appId: '1:732995322952:web:3a696d185755e3c1cdc47d',
    messagingSenderId: '732995322952',
    projectId: 'auth-d10f1',
    authDomain: 'auth-d10f1.firebaseapp.com',
    storageBucket: 'auth-d10f1.firebasestorage.app',
    measurementId: 'G-36KHK8B59J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVfzT4p2DLRABa4lOP6zsTIvQ5QH4Hhh0',
    appId: '1:732995322952:android:270f7de5a665bed5cdc47d',
    messagingSenderId: '732995322952',
    projectId: 'auth-d10f1',
    storageBucket: 'auth-d10f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3z9oILFKjwOOABAIWgCJEXpcd5oLwzY',
    appId: '1:732995322952:ios:db546aeed5dc916acdc47d',
    messagingSenderId: '732995322952',
    projectId: 'auth-d10f1',
    storageBucket: 'auth-d10f1.firebasestorage.app',
    iosBundleId: 'com.example.appAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3z9oILFKjwOOABAIWgCJEXpcd5oLwzY',
    appId: '1:732995322952:ios:db546aeed5dc916acdc47d',
    messagingSenderId: '732995322952',
    projectId: 'auth-d10f1',
    storageBucket: 'auth-d10f1.firebasestorage.app',
    iosBundleId: 'com.example.appAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIgvi7_KlIXxcJAdAXF-h7XEnBF48T6u8',
    appId: '1:732995322952:web:a5f2cfb06b602c3fcdc47d',
    messagingSenderId: '732995322952',
    projectId: 'auth-d10f1',
    authDomain: 'auth-d10f1.firebaseapp.com',
    storageBucket: 'auth-d10f1.firebasestorage.app',
    measurementId: 'G-FLF3VGQ59Y',
  );
}
